name: articleTweet
on:
  schedule:
    - cron: "0 */3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Doing tweet
        run: curl https://personaltwitterbot1.herokuapp.com/articletweet
