# This is a basic workflow to help you get started with Actions

name: follow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
   schedule:
    - cron: "*/60 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Getting all videos
      run: curl https://personaltwitterbot.herokuapp.com/follow
