# This is a basic workflow to help you get started with Actions

name: FetchVideos_On_Push

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name:  fetchin videos
      run: curl https://personaltwitterbot.herokuapp.com/getVideos
