name: RETWEET
on:
  schedule:
    - cron: "*/55 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Doing retweet
        run: curl https://personaltwitterbot1.herokuapp.com/retweet
