name: TWEET
on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Doing tweet
      run: curl https://personaltwitterbot.herokuapp.com/tweet
